CONTENT_TYPE_APPLICATION: str = "application"
CONTENT_TYPE_JSON: str = f"{CONTENT_TYPE_APPLICATION}/json"

CONTEXT_VARIABLE_CONTEXT: str = "context"

EMPTY_STRING: str = ""

ENCODING_UTF8: str = "utf-8"
ENCODING_JSON: str = ENCODING_UTF8

FILE_IGNORE_ERRORS: str = "ignore"
FILE_MODE_APPEND: str = "a"
FILE_MODE_BINARY: str = "b"
FILE_MODE_READ: str = "r"
FILE_MODE_READ_BINARY: str = FILE_MODE_READ + FILE_MODE_BINARY
FILE_MODE_WRITE: str = "w"
FILE_MODE_WRITE_BINARY: str = FILE_MODE_WRITE + FILE_MODE_BINARY

INDENT_JSON: int = 2

HYPERTEXT_TRANSFER_HEADER_KEY_LINK: str = "Link"
HYPERTEXT_TRANSFER_HEADER_KEY_LOCATION: str = "Location"
HYPERTEXT_TRANSFER_PROTOCOL: str = "http"
HYPERTEXT_TRANSFER_PROTOCOL_METHOD_GET: str = "GET"
HYPERTEXT_TRANSFER_PROTOCOL_METHOD_POST: str = "POST"

LANGCHAIN_CONFIGURATION_KEY_THREAD_IDENTIFIER: str = "thread_id"

LINE_BREAK_CARRIAGE_RETURN: str = "\r"
LINE_BREAK_NEW_LINE: str = "\n"
LINE_BREAK_CARRIAGE_RETURN_LINE_FEED: str = LINE_BREAK_CARRIAGE_RETURN + LINE_BREAK_NEW_LINE

OPEN_AI_KEY_NONE: str = "EMPTY"

SEPARATOR_SEGMENT: str = "/"

SPACE: str = " "

THREAD_POOL_SIZE: int = 10




