from typing import Literal

CONTENT_TYPE_APPLICATION: str = "application"
CONTENT_TYPE_JSON: str = f"{CONTENT_TYPE_APPLICATION}/json"

CONTEXT_KEY_ACTIVITY: str = "activity"
CONTEXT_KEY_COMMAND: str = "command"
CONTEXT_KEY_FILE: str = "target_file"
CONTEXT_KEY_MODULE: str = "target_module"
CONTEXT_KEY_PHASE: str = "phase"
CONTEXT_KEY_SESSION: str = "session"
CONTEXT_KEY_TOOL: str = "tool"
CONTEXT_VARIABLE_CONTEXT: str = "context"

EMPTY_STRING: str = ""

ENCODING_UTF8: str = "utf-8"
ENCODING_JSON: str = ENCODING_UTF8

DATETIME_FORMAT_ROUNDTRIP: str = "%Y-%m-%dT%H:%M:%S.%fZ"

EXTENSION_SEPARATOR: str = "."
EXTENSION_BACKUP: str = EXTENSION_SEPARATOR + "so" + EXTENSION_SEPARATOR + "bak"
EXTENSION_COMMA_SEPARATED_VALUES: str = EXTENSION_SEPARATOR + "csv"
EXTENSION_COMPRESSED_GZIP: str = EXTENSION_SEPARATOR + "gz"
EXTENSION_JSON: str = EXTENSION_SEPARATOR + "json"
EXTENSION_MACHINE_OBJECT: str = EXTENSION_SEPARATOR + "mo"
EXTENSION_ORIGINAL: str = EXTENSION_SEPARATOR + "orig"
EXTENSION_PORTABLE_OBJECT: str = EXTENSION_SEPARATOR + "po"
EXTENSION_TEXT: str = EXTENSION_SEPARATOR + "txt"

FILE_IGNORE_ERRORS: str = "ignore"
FILE_MODE_APPEND: str = "a"
FILE_MODE_BINARY: str = "b"
FILE_MODE_READ: str = "r"
FILE_MODE_READ_BINARY: str = FILE_MODE_READ + FILE_MODE_BINARY
FILE_MODE_WRITE: str = "w"
FILE_MODE_WRITE_BINARY: str = FILE_MODE_WRITE + FILE_MODE_BINARY

FINISH_REASON_CONTENT_FILTER: str = "content_filter"
FINISH_REASON_FUNCTION_CALL: str = "function_call"
FINISH_REASON_LENGTH: str = "length"
FINISH_REASON_STOP: str = "stop"
FINISH_REASON_KEY_OPEN_AI: str = "finish_reason"

INDENT_JSON: int = 2

HYPERTEXT_TRANSFER_HEADER_KEY_LINK: str = "Link"
HYPERTEXT_TRANSFER_HEADER_KEY_LOCATION: str = "Location"
HYPERTEXT_TRANSFER_PROTOCOL: str = "http"
HYPERTEXT_TRANSFER_PROTOCOL_METHOD_GET: str = "GET"
HYPERTEXT_TRANSFER_PROTOCOL_METHOD_POST: str = "POST"

LANGCHAIN_CONFIGURATION_KEY_THREAD_IDENTIFIER: str = "thread_id"

LANGUAGE_EMBEDDING_MODEL: str = "openai:text-embedding-3-small"
LANGUAGE_EMBEDDING_MODEL_RETRIEVAL_AUGMENTED_GENERATION: str = "text-embedding-3-large"
LANGUAGE_INDEX_DIMENSIONS: int = 1536
LANGUAGE_MODEL_GOOGLE_DEFAULT: str = "gemini-2.5-pro"
LANGUAGE_MODEL_GOOGLE_INPUT_LIMIT: int = 1000000
LANGUAGE_MODEL_OPEN_AI_GPT4: str = "gpt-4.1"
LANGUAGE_MODEL_OPEN_AI_GPT5: str = "gpt-5.1"
LANGUAGE_MODEL_OPEN_AI_O3: str = "o3"
LANGUAGE_MODEL_OPEN_AI_CHAT_DEFAULT: str = LANGUAGE_MODEL_OPEN_AI_GPT5
LANGUAGE_MODEL_OPEN_AI_REASON_DEFAULT: str = LANGUAGE_MODEL_OPEN_AI_GPT5
LANGUAGE_MODEL_OPEN_AI_INPUT_LIMIT: int = 100000
LANGUAGE_MODEL_PROVIDER_GOOGLE: str = "Google"
LANGUAGE_MODEL_PROVIDER_OPEN_AI: str = "OpenAI"
LANGUAGE_MODEL_TIMEOUT_IN_SECONDS: float = 15.0 * 60.0

LANGGRAPH_CONFIGURATION_KEY_THREAD_IDENTIFIER: str = "thread_id"
LANGGRAPH_INPUT_OUTPUT_KEY_MESSAGES: str = "messages"
LANGGRAPH_OUTPUT_MODE_FULL_HISTORY: Literal["full_history","last_message"] = "full_history"
LANGGRAPH_OUTPUT_MODE_LAST_MESSAGE: Literal["full_history","last_message"] = "last_message"

LINE_BREAK_CARRIAGE_RETURN: str = "\r"
LINE_BREAK_NEW_LINE: str = "\n"
LINE_BREAK_CARRIAGE_RETURN_LINE_FEED: str = LINE_BREAK_CARRIAGE_RETURN + LINE_BREAK_NEW_LINE

OPEN_AI_KEY_NONE: str = "EMPTY"
OPEN_AI_TEMPERATURE_DEFAULT: float = 0.0
OPEN_AI_TEMPERATURE_03: int = 1
OPEN_AI_TIMEOUT_IN_SECONDS: int = 6 * 60

SEPARATOR_SEGMENT: str = "/"

SPACE: str = " "

THREAD_POOL_SIZE: int = 10

UNKNOWN: str = "?"




